### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by escalade** [duganchen/dosbox#12]
Been using your fork for a while now, just wanted to say thank you for your hard work. I've tested it on both RPi3 and Intel, it works very nicely with SDL2 and the shader support is pure awesome. I did some testing adding back the MT-32 support as well and it sounds perfect for me on Monkey Island 2, perhaps you should consider adding it back?

I'm using your fork in my LibreELEC fork, hope you don't mind:

https://forum.libreelec.tv/thread/302-le8-remix-generic-rpi-emulationstation-chrome-spotify-provide-logs-if-problems/

:-)

**Comment by duganchen** [comment]
Hey, awesome! Thanks for the feedback!

Since you're using this as the base for another fork, you might want to look at the series of patches I released to turn DosBox into this:

http://www.vogons.org/viewtopic.php?f=41&t=43068&start=20

I'm going to close the issue, but feel free to keep using it for discussion.
